name: Pytest
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest  # or another OS like macos-latest or windows-latest
    
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests with pytest
      run: python -m pytest ./royal_game/tests/  # Assuming your tests are in the "tests" directory